version: '3'

networks:
  api:
    external: true

services:
  api:
    container_name: api
    build: .
    ports:
      - 8282:8282
    volumes:
      - ./db.json:/dev/fakeapi/db.json
    command: json-server db.json --p 8282